spring.application.name=vbs-system

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/vbs_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JSP CONFIG
# ===============================
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.main.web-application-type=servlet

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================
server.port=8080